packages:
  - packages/*
  - apps/*

catalog:
  '@effect/language-service': ^0.86.2
  '@effect/opentelemetry': 4.0.0-beta.78
  '@effect/platform-browser': 4.0.0-beta.51
  '@effect/platform-node': 4.0.0-beta.78
  effect: 4.0.0-beta.51
  oxfmt: ^0.53.0
  oxlint: ^1.68.0
  typescript: 6.0.3
