import { ProcedureStack, ProcedureStep } from "@mrt/yamcs-effect";

export const TW1 = ProcedureStack.make({
  steps: [
    ProcedureStep.make({
      type: "note",
      text: "Prop/AV and Testing Procedures",
      color: "#B892B6",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 1,
      role: "AES & AVC",
      text: "Hold and align the AV Bay so that the backplane is closest to the rail.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 2,
      role: "AES & AVC",
      text: "AVC keeps holding the AV bay while AEC screws in the 6-32 fasteners through the AV plate into the vent radax.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 3,
      role: "AVC",
      text: "Screw Prop Top into the Prop Top mount using 4 4-40 fasteners.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 4,
      role: "AVC & PRC",
      text: "Attach the Tank PT wires to a SE ModPT DB PCB. Be careful of wire polarity. Black goes to the -, red goes to 5 V, green goes to PT.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 5,
      role: "AVC",
      text: "Attach the ModPT SE DB to Prop Top.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 6,
      role: "AVC & PRC",
      text: "Attach the Vent TC to Prop Top. There is no wire polarity.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 7,
      role: "AVC & PRC",
      text: "Attach the vent valve wires to the valve terminal block on Prop Top. There is no wire polarity.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 8,
      role: "AVC & PRC",
      text: "Screw Prop Bottom into the prop bottom mount using 4 4-40 fasteners.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 9,
      role: "AVC & PRC",
      text: "Screw the CC PT wires into the ModPT DB on prop bottom. Be careful of wire polarity.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 10,
      role: "AVC & PRC",
      text: "Screw the Tank TC wires into Prop Bottom. There is no wire polarity.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 11,
      role: "AVC & PRC",
      text: "Screw the F/DOV wires into the FDOV terminal block on Prop Bottom. The FDOV terminal block is the big 2-pin terminal block closest to the top right corner of the PCB. There is no wire polarity.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 12,
      role: "AVC & PRC",
      text: "Screw the MOV wires into the MOV terminal block on Prop Bottom. The MOV terminal block is the terminal big 2-pin terminal block closest to the Prop Top-to-Prop Bottom wire harness connector. There is no wire polarity.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 13,
      role: "AVC",
      text: "Attach the Prop Top to Backplane wiring harness.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 14,
      role: "AVC",
      text: "Attach the Prop Top to Prop Bottom wiring harness.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 15,
      role: "AVC",
      text: "Secure the Prop Top to Prop Bottom Harness to the tank using Aluminum tape.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 16,
      role: "AVC",
      text: "Connect the Backplane-Power Supply harness.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 17,
      role: "AVC",
      text: "Set the DC Power supply to 25.2V at 2.0A, and turn the output on.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 18,
      role: "AVC",
      text: "Arm SRAD Avionics.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "AV-Propulsion Integration & Telemetry Verification",
      color: "#FFBF80",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 19,
      role: "CSH",
      name: "/FlightComputer/reset_av",
      comment: "Press the command stack button to Reset AV.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 20,
      role: "AVC",
      text: "Confirm FC-A reboots.\nConfirm FC-B reboots.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 21,
      role: "CSC",
      text: "Confirm the ACK for the Reset AV command.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 22,
      role: "CSH",
      name: "/FlightComputer/propulsion_on",
      comment: "Press the command stack button to set Propulsion On.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 23,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalArm", label: "armed_SW" },
          { id: "electricalArm", label: "armed_HW" },
          { id: "continuity", label: "continuity_HW" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_armed_SW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_armed_HW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "continuity" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_armed_SW",
          operator: "eq",
          value: true,
          display: { row: "Vent Valve", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_armed_HW",
          operator: "eq",
          value: true,
          display: { row: "Vent Valve", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "Vent Valve", column: "continuity" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_logical_SW",
          operator: "eq",
          value: false,
          display: { row: "MOV", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_electrical_HW",
          operator: "eq",
          value: false,
          display: { row: "MOV", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "MOV", column: "continuity" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 24,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      off  off   off on",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off on",
        "Confirm the LEDs on the Prop Top Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 25,
      role: "CSC",
      comment: "Verify that the Tank Pressure reading is within 0.0 to 20.0 PSI.",
      delay: 0,
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/tank_pressure",
          operator: "gte",
          value: 0,
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/tank_pressure",
          operator: "lte",
          value: 20,
        },
      ],
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 26,
      role: "CSC",
      comment: "Verify that the Vent Temperature reading is within 12.0 to 30.0 C.",
      delay: 0,
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_temp",
          operator: "gte",
          value: 12,
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_temp",
          operator: "lte",
          value: 30,
        },
      ],
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 27,
      role: "CSC",
      comment: "Verify that the Combustion Chamber Pressure reading is within 0.0 to 20.0 PSI.",
      delay: 0,
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/cc_pressure",
          operator: "gte",
          value: 0,
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/cc_pressure",
          operator: "lte",
          value: 20,
        },
      ],
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 28,
      role: "CSC",
      comment: "Verify that the Tank Temperature reading is within 12.0 to 30.0 C.",
      delay: 0,
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/tank_temp",
          operator: "gte",
          value: 12,
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/tank_temp",
          operator: "lte",
          value: 30,
        },
      ],
    }),
    ProcedureStep.make({
      type: "note",
      text: "Basic Vent Valve Verification",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 29,
      role: "PRC",
      text: "Place 2 fingers on the vent valve to feel for gate actuation.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 30,
      role: "CSH",
      name: "/FlightComputer/vent_valve_energize",
      comment: "Set the Vent Valve switch to ENERGIZED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 31,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energized_SW",
          operator: "eq",
          value: true,
          display: { row: "Vent Valve", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedGate_HW",
          operator: "eq",
          value: true,
          display: { row: "Vent Valve", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "Vent Valve", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 32,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Top Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   on    on  on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 33,
      role: "CSH",
      name: "/FlightComputer/vent_valve_de-energize",
      comment: "Set the Vent Valve switch to DE-ENERGIZED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 34,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energized_SW",
          operator: "eq",
          value: false,
          display: { row: "Vent Valve", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedGate_HW",
          operator: "eq",
          value: false,
          display: { row: "Vent Valve", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "Vent Valve", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 35,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Top Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 36,
      role: "CSH",
      name: "/FlightComputer/reset_av",
      comment: "Press the command stack button to Reset AV.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 37,
      role: "AVC",
      text: "Confirm FC-A reboots.\nConfirm FC-B reboots.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 38,
      role: "CSC",
      text: "Confirm the ACK for the Reset AV command.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Basic MOV Verification",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 39,
      role: "PRC",
      text: "Place 2 fingers on the MOV to feel for gate actuation.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 40,
      role: "CSH",
      comment: "Insert and turn the key switch clockwise to switch MOV to ARMED.",
      name: "/FlightComputer/mov_arming",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 41,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalArm", label: "armed_SW" },
          { id: "electricalArm", label: "armed_HW" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_logical_SW",
          operator: "eq",
          value: true,
          display: { row: "MOV", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_electrical_HW",
          operator: "eq",
          value: true,
          display: { row: "MOV", column: "electricalArm" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 42,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 43,
      role: "CSC",
      comment: "Press the Launch button.",
      name: "/FlightComputer/launch",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 44,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   on    on  on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 45,
      role: "PRC",
      text: "Confirm that the MOV solenoid de-energizes after 5 seconds.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 46,
      role: "CSH",
      comment: "Turn the key switch counter clockwise to switch MOV to DISARMED.",
      name: "/FlightComputer/mov_disarming",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 47,
      role: "CSH",
      text: "Remove the key from the key switch.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 48,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalArm", label: "armed_SW" },
          { id: "electricalArm", label: "armed_HW" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_logical_SW",
          operator: "eq",
          value: false,
          display: { row: "MOV", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_electrical_HW",
          operator: "eq",
          value: false,
          display: { row: "MOV", column: "electricalArm" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 49,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      off  off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "note",
      text: "Basic F/DOV Verification",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 50,
      role: "PRC",
      text: "Place 2 fingers on the F/DOV to feel for gate actuation.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 51,
      role: "CSH",
      name: "/FlightComputer/fdov_energize",
      comment: "Set the F/DOV switch to ENERGIZED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 52,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energized_SW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedGate_HW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 53,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   on    on  on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 54,
      role: "CSH",
      name: "/FlightComputer/fdov_de-energize",
      comment: "Set the F/DOV switch to DE-ENERGIZED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 55,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energized_SW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedGate_HW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 56,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "note",
      text: "Abort Functional Verification",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 57,
      role: "CSH",
      name: "/FlightComputer/mov_arming",
      comment: "Insert and turn the key switch clockwise to switch MOV to ARMED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 58,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalArm", label: "armed_SW" },
          { id: "electricalArm", label: "armed_HW" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_logical_SW",
          operator: "eq",
          value: true,
          display: { row: "MOV", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/mov_armed_electrical_HW",
          operator: "eq",
          value: true,
          display: { row: "MOV", column: "electricalArm" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 59,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 60,
      role: "CSH",
      name: "/FlightComputer/fdov_energize",
      comment: "Set the F/DOV switch to ENERGIZED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 61,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energized_SW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedGate_HW",
          operator: "eq",
          value: true,
          display: { row: "F/DOV", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 62,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   on    on  on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 63,
      role: "CSH",
      name: "/FlightComputer/vent_valve_energize",
      comment: "Set the Vent switch to ENERGIZED.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 64,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energized_SW",
          operator: "eq",
          value: true,
          display: { row: "Vent", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedGate_HW",
          operator: "eq",
          value: true,
          display: { row: "Vent", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "Vent", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 65,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Top Energize Daughter Board are as follows:",
        "  Channel  CON  GATE  EN  ARM",
        "  CH1      on   on    on  on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 66,
      role: "CSH",
      comment: "Press the Launch button.",
      name: "/FlightComputer/launch",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 67,
      role: "PRC",
      text: "Confirm MOV actuation.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 68,
      role: "CSH",
      name: "/FlightComputer/emergency_stop",
      comment: "Press the E-Stop Button.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 69,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalEnergized", label: "Logical Energize" },
          { id: "energizeGate", label: "Energize Gate" },
          { id: "energizeCurrent", label: "Energize Current" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energized_SW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedGate_HW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/fdov_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "F/DOV", column: "energizeCurrent" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energized_SW",
          operator: "eq",
          value: false,
          display: { row: "Vent", column: "logicalEnergized" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedGate_HW",
          operator: "eq",
          value: false,
          display: { row: "Vent", column: "energizeGate" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/vent_energizedCurrent_HW",
          operator: "eq",
          value: false,
          display: { row: "Vent", column: "energizeCurrent" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the valve states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 70,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Bottom Energize Daughter Board are as follows:",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 71,
      role: "AVC",
      text: [
        "Confirm the LEDs on the Prop Top Energize Daughter Board are as follows:",
        "  Channel  CON  GATE  EN  ARM",
        "  CH1      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 72,
      role: "AVC",
      text: "Turn off the Power Supply.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 73,
      role: "AVC",
      text: "Disconnect the Power Umbilical-Power Supply cable.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 74,
      role: "AVC & PRC",
      text: "Connect the Umbilical Panel to the Vent Radax using 4 6-32 fasteners.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 75,
      role: "AVC",
      text: "Connect the Male Power Umbilical connector to the rocket.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 76,
      role: "AVC",
      text: "Connect the Male Power Umbilical harness to a DC power supply.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 77,
      role: "PRC",
      text: "Lubricate the male QC on the F/DOV with Krytox.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 78,
      role: "AEC & PRC",
      text: "Secure panels to radaxes excluding the panels covering the prop boards, ensure all vent lines are routed out of the panels and are covered loosely to prevent dust from entering the lines.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 79,
      role: "AEC & PRC",
      text: "ENSURE THAT THE MANUAL DUMP VALVE IS CLOSED.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "The AV-Prop sub-assembly is complete.",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Final Rocket Assembly Procedures.",
      color: "#A3C293",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 1,
      role: "AEC",
      text: "Fasten main set of shear pins using 6 #8-32 shear pins",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 2,
      role: "AEC & EJC",
      text: "Slide the nose cone over the drogue plate and coupler, secure with 6 #6-32 shear pins",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 3,
      role: "AVC",
      text: "Attach the Payload Harness between the IEPE adapter PCB & the Backplane PCB.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 4,
      role: "AVC",
      text: "Attach one end of the COTS Main Recov harness to the Main Channel on the Blue Raven.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 5,
      role: "AVC",
      text: "Attach the other end of the COTS Main Recov harness to COTS Vdd wago connector.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 6,
      role: "AVC",
      text: "Attach one end of the COTS Drogue Recov harness to the Apo Channel on the Blue Raven.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 7,
      role: "AVC",
      text: "Attach the other end of the COTS Main Recov harness to COTS Vdd wago connector.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 8,
      role: "AVC",
      text: "Arm COTS avionics.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 9,
      role: "AVC",
      text: "Confirm Blue Raven continuity_HW by listening for two beeps, and seeing two green LED flashes.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 10,
      role: "AVC",
      text: "Verify Blue Raven is properly configured using Blue Raven Mobile App.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 11,
      role: "AVC",
      text: "Disarm COTS avionics.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 12,
      role: "AVC",
      text: "Switch the Featherweight GPS tracker power switch to on.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 13,
      role: "CSC",
      text: "Verify the reception of packets on the Featherweight GPS Tracker ground station using the Blue Raven Mobile app.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "The COTS avionics system is validated for flight.",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 14,
      role: "AVC",
      text: "Connect the SRAD Drogue Ejection wires to Channel 1 of both SRAD FCs.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 15,
      role: "AVC",
      text: "Connect the SRAD Drogue Main wires to Channel 2 of both SRAD FCs.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Recovery Sub-System Command and Telemetry Verification",
      color: "#FFBF80",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 16,
      role: "CSH",
      name: "/FlightComputer/reset_av",
      comment: "Press the command stack button to Reset AV.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 17,
      role: "AVC",
      text: "Confirm FC-A reboots.\nConfirm FC-B reboots.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 18,
      role: "CSC",
      text: "Confirm the ACK for the Reset AV command.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 19,
      role: "CSH",
      name: "/FlightComputer/arm_recovery",
      comment: "Press the command stack button to set Recovery Arm.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 20,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalArm", label: "armed_SW" },
          { id: "electricalArm", label: "armed_HW" },
          { id: "continuity", label: "continuity_HW" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_SW",
          operator: "eq",
          value: true,
          display: { row: "Drogue", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_HW",
          operator: "eq",
          value: true,
          display: { row: "Drogue", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/drogue_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "Drogue", column: "continuity" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/main_armed_SW",
          operator: "eq",
          value: true,
          display: { row: "Main", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/main_armed_HW",
          operator: "eq",
          value: true,
          display: { row: "Main", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/main_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "Main", column: "continuity" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the ejection channel states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 21,
      role: "AVC",
      text: [
        "Confirm the LEDs on the FC-A Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   off   off on",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off on",
        "Confirm the LEDs on the FC-B Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      on   off   off on",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off on",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 22,
      role: "CSH",
      name: "/FlightComputer/disarm_recovery",
      comment: "Press the command stack button to set Recovery Disarm.",
    }),
    ProcedureStep.make({
      type: "verify",
      stepNumber: 23,
      role: "CSC",
      presentation: {
        type: "truthTable",
        columns: [
          { id: "logicalArm", label: "armed_SW" },
          { id: "electricalArm", label: "armed_HW" },
          { id: "continuity", label: "continuity_HW" },
        ],
      },
      condition: [
        {
          parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_SW",
          operator: "eq",
          value: false,
          display: { row: "Drogue", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_HW",
          operator: "eq",
          value: true,
          display: { row: "Drogue", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/drogue_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "Drogue", column: "continuity" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/main_armed_SW",
          operator: "eq",
          value: false,
          display: { row: "Main", column: "logicalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/main_armed_HW",
          operator: "eq",
          value: true,
          display: { row: "Main", column: "electricalArm" },
        },
        {
          parameter: "/SystemA/Rocket/FlightComputer/main_continuity_HW",
          operator: "eq",
          value: true,
          display: { row: "Main", column: "continuity" },
        },
      ],
      delay: 0,
      comment:
        "Confirm that the completion ACK is received.\nConfirm the ejection channel states are as follows:",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 24,
      role: "AVC",
      text: [
        "Confirm the LEDs on the FC-A Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      off  off   off on",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off off",
        "Confirm the LEDs on the FC-B Energize Daughter Board are as follows:",
        "  Channel  ARM  GATE  EN  CON",
        "  CH1      off  off   off on",
        "  Channel  CON  GATE  EN  ARM",
        "  CH2      on   off   off off",
      ].join("\n"),
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 25,
      role: "AVC",
      text: "Verify that Payload Electronics are functioning nominally.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 26,
      role: "AVC",
      text: "Disarm SRAD avionics.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "The SRAD avionics system is validated for flight.",
      color: "#FFF798",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 27,
      role: "AEC & AVC",
      text: "Slide GFRP over AV bay. Be careful of the MagSW Mount and payload wiring",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 28,
      role: "AEC",
      text: "Secure GFRP to vent radax",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 29,
      role: "AEC",
      text: "Fasten nose cone using 8 #10-32 low profile fasteners",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 30,
      role: "RCC & EJC",
      text: "Use quicklink to connect AA section of harness to harness section A and the drogue plate.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 31,
      role: "AEC & RCC",
      text: "Slide nose cone over the coupler secure with 6 #6-32 shear pins",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 32,
      role: "PRC",
      text: "Close the MOV.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 33,
      role: "AEC",
      text: "Verify panels have been secured",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 34,
      role: "PRC & AEC",
      text: "Wrap tank wires in extra sticker section for aesthetic purposes (omittable)",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 35,
      role: "AEC & PRC",
      text: "Attach remaining 2 radax panels using 8 #8-32 fasteners.",
    }),
  ],
});
