import { ProcedureStack, ProcedureStep } from "@mrt/yamcs-effect";

export const TW2 = ProcedureStack.make({
  steps: [
    ProcedureStep.make({
      type: "note",
      text: "Warning: The rocket contains black powder. Keep the nose cone pointed in a safe direction. Personnel should not stand in front of the nose cone.",
      color: "#FEBFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 1,
      role: "AD",
      text: "Designate an assembler from each subteam to pack any hardware or tools to be brought to the launch pad (into the pickup truck if necessary).",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 2,
      role: "AD",
      text: "Direct assembly team to transport the rocket to the flight safety tent.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 3,
      role: "PD",
      text: "Wait for flight approval. If time allows, verify the state of the launch pad in preparation for launch procedures (generator gas level, valve states, etc.).",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 4,
      role: "AD",
      text: "Receive flight approval.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "If flight approval is not granted, return to the assembly tents to rectify the issue; inform the pad and the ground station. Then restart these procedures.",
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 5,
      role: "AD",
      text: "Inform the ground station and the launch pad that flight approval has been granted.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 6,
      role: "AD",
      text: "Load the rocket onto the pickup truck. Wait for the range to open.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 7,
      role: "OP3",
      text: "Turn on the launch pad generator and the pad box. Make sure to switch on all the breakers in the pad box.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 8,
      role: "AD",
      text: "Drive the rocket to the launch pad. The whole team should come as well.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 9,
      role: "PD",
      text: "Go to tower raising final checklist and confirm that the rocket can be installed on the launch rail.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 10,
      role: "PD",
      text: "Direct the operators to transport the rocket from the pickup truck to the end of the launch rail.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 11,
      role: "PD",
      text: "Slowly guide the rocket onto the launch rail with the help of the operators. There are 2 rail buttons. Take care to not scratch the rocket sticker.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 12,
      role: "OP1",
      text: "Securely fasten the rail stop.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 13,
      role: "OP3",
      text: "Mount the AV Power Umbilical Box to the base of the Tower. Slide the electromagnet mounts along the rail until the indicated position on the rocket. Securely fasten.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 14,
      role: "OP2 & OP4",
      text: "Install the fill arm to the tower and install the gantry to the fill arm. Connect the QC to the FDOV and fasten the gripping mechanism. Prepare the retraction and separation mechanisms. See Disconnect Installation procedures [Pad4].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 15,
      role: "OP1",
      text: "Remove the bags from the vent line and the PRV.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 16,
      role: "LD & OP3",
      text: "Make sure that the camera angles are acceptable.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 17,
      role: "PD",
      text: "Once proper alignment of the fill arm is confirmed, perform a pull test on the fill line to ensure the quick connect is properly connected.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 18,
      role: "OP3",
      text: "Verify all electrical connections are continuous to components of the launch pad.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 19,
      role: "OP5",
      text: "Remove any protective padding from the nose cone.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 20,
      role: "PD",
      text: "Go to Tower Raising Procedures [Pad3]",
    }),
    ProcedureStep.make({
      type: "note",
      text: "At this point, only required tower raising personnel and operators should be in the safety perimeter of the launch tower. All of them must be wearing yellow jackets, hard hats, safety shoes, and coated gloves.",
      color: "#FEBFBF",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Proceed once the launch rail is raised.\nLAUNCH DIRECTOR: if disconnection testing is being skipped, proceed to step 38",
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 21,
      role: "PD to LD",
      text: "Inform LD that the pad is ready for disconnection testing",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 22,
      role: "PD",
      text: "Check that the breakers required for disconnection and retraction are on.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 23,
      role: "CS",
      commands: [
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 5 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 7 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
      ],
      comment:
        "Actuate the DIS linear actuator to retract by energizing DIS Actuator Polarity and DIS Actuator Power on the control box, broadcasting a countdown from 3 for both.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 24,
      role: "PD to LD",
      text: "Confirm successful disengagement.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 25,
      role: "CS",
      commands: [
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 4 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 6 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
      ],
      comment:
        "Actuate the RET linear actuator to retract by energizing RET Actuator Polarity and RET Actuator Power on the control box, broadcasting a countdown from 3 for both.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 26,
      role: "PD to LD",
      text: "Confirm successful retraction.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 27,
      role: "CS",
      commands: [
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 7 },
            { name: "pin_state", value: "LOW" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 6 },
            { name: "pin_state", value: "LOW" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 5 },
            { name: "pin_state", value: "LOW" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 4 },
            { name: "pin_state", value: "LOW" },
          ],
        },
      ],
      comment:
        "De-energize Actuators Power (both DIS and RET) and Actuators Polarity (both DIS and RET) on the control box.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 28,
      role: "CS",
      commands: [
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 4 },
            { name: "pin_state", value: "LOW" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 6 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
      ],
      comment:
        "Actuate RET linear actuator to extend by energizing RET Actuator Power on the control box, broadcasting a countdown from 3.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 29,
      role: "PD",
      text: "Confirm RET actuator has extended to full stroke.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 30,
      role: "PD",
      text: "Go to Tower Lowering Procedures [Pad3]",
    }),
    ProcedureStep.make({
      type: "note",
      text: "At this point, only required tower raising personnel and operators should be in the safety perimeter of the launch tower. All of them must be wearing yellow jackets, hard hats, safety shoes, and coated gloves.",
      color: "#FEBFBF",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Proceed once the launch rail is lowered.",
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 31,
      role: "OP5",
      text: "Check that the rail stop is properly fastened.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 32,
      role: "OP2 & OP4",
      text: "Reconnect the fill disconnection system to the rocket, following disconnect assembly procedures [Pad4].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 33,
      role: "LD",
      text: "On the go of OP2, extend the DIS linear actuator by energizing DIS actuator power.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 34,
      role: "OP2 & OP4",
      text: "Perform a pull test on the fill line to ensure the quick connect is properly connected.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 35,
      role: "PD & OP4",
      text: "Once proper alignment of the fill arm is confirmed, perform a second pull test on the fill line to ensure the quick connect is properly connected.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 36,
      role: "OP3",
      text: "Confirm that all connections from padbox to launch pad components are continuous.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 37,
      role: "PD",
      text: "Go to Tower Raising Procedures [Pad3]",
    }),
    ProcedureStep.make({
      type: "note",
      text: "At this point, only required tower raising personnel and operators should be in the safety perimeter of the launch tower. All of them must be wearing yellow jackets, hard hats, safety shoes, and coated gloves.",
      color: "#FEBFBF",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Proceed once the launch rail is raised. Remove the igniter shield for the team picture.",
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 38,
      role: "All",
      text: "Take a quick group picture! Then, all non-essential launch pad personnel must leave the safety perimeter of the launch rail.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 39,
      role: "All",
      text: "All personnel except PD, OP1, OP2, OP3, OP4, OP5 exit the launch pad and head back to the ground station. Re-install the igniter shield.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 40,
      role: "OP3",
      text: "Connect AV umbilical box to the external power supply.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 41,
      role: "PD to LD",
      text: "Broadcast that the SRAD system is about to be turned on",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 42,
      role: "OP3",
      text: "Turn on the SRAD system with the SRAD electromagnet by flipping the SRAD switch to the on/off position on the AV umbilical Box.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 43,
      role: "CS to PD",
      text: "Confirm reception of telemetry from the AV bay over radio.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 44,
      role: "CS to PD",
      text: "Confirm payload data is being received on GUI.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 45,
      role: "CS",
      name: "/FlightComputer/propulsion_on",
      comment: 'Energize the propulsion controllers by pressing the "Prop On" button on the GUI.',
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 46,
      role: "CS",
      text: "Confirm that the tank pressure is reading ambient conditions: ____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 47,
      role: "CS",
      text: "Confirm that the combustion chamber pressure is reading ambient conditions: ____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 48,
      role: "CS",
      text: "Confirm that the tank temperature is reading ambient conditions: ____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 49,
      role: "CS",
      text: "Confirm that the vent temperature is reading ambient conditions: ____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 50,
      role: "CS",
      text: "Confirm that both pad pressure transducers are reading ambient conditions: ____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 51,
      role: "CS",
      text: "Confirm that the pad temperature is reading ambient conditions: ____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 52,
      role: "CS",
      text: "Confirm that the GPS data is credible. It should indicate a position near Launch Canada Vertical Launch Area, 47.98737, -81.84874. Note the values: ________________________________",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 53,
      role: "CS",
      text: "Confirm that the altitude gives credible data. Launch Canada is at approx. 400m. Note the values: ________________________________",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 54,
      role: "LD to PD",
      text: "Inform that GUI checks are complete and we are ready to proceed with valve checks",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 55,
      role: "PD",
      text: "Inform operators to go to valve check positions (OP1 by rocket valves, OP3 by padbox, OP2 by gas bottles, OP4-5 in front of fill panel",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 56,
      role: "PD to LD",
      text: "Confirm that the nitrous mother tank needle valve [V-20] is fully closed.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 57,
      role: "PD to LD",
      text: "Confirm that the nitrogen mother tank needle valve [V-50] is fully closed.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 58,
      role: "PD to LD",
      text: "Confirm that the pad manual dump valves [V-21], [V-24] and the rocket manual dump are fully closed.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 59,
      role: "LD to PD",
      text: "Announce the start of valve actuation tests over radio",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 60,
      role: "CS",
      commands: [
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 0 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 0 },
            { name: "pin_state", value: "LOW" },
          ],
        },
      ],
      comment:
        "Energize to open and de-energize to close the panel fill valve [V-22] after countdown from 3 over radio. Confirm actuation using cameras and operators.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 61,
      role: "CS to PD",
      commands: [
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 1 },
            { name: "pin_state", value: "HIGH" },
          ],
        },
        {
          name: "/LabJackT7/write_digital_pin",
          arguments: [
            { name: "pin_number", value: 1 },
            { name: "pin_state", value: "LOW" },
          ],
        },
      ],
      comment:
        "Energize to close and de-energize to open the panel dump valve [V-23] after countdown from 3 over radio. Confirm actuation using cameras and operators.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 62,
      role: "CS to PD",
      commands: [
        {
          name: "/FlightComputer/fdov_energize",
        },
        {
          name: "/FlightComputer/fdov_de-energize",
        },
      ],
      comment:
        "Energize and de-energize the FDOV pilot [V-10] after countdown from 3 over radio: Confirm that the Fill-Dump Oxidizer Valve is energized by hearing a 'click' sound from its pilot and receiving an acknowledgment. The FDOV valve [V-11] should not actuate at this point.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 63,
      role: "CS",
      name: "",
      comment: "Arm the control box with the testing arming key.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 64,
      role: "CS",
      name: "",
      comment: "Confirm that there is continuity of the Main Oxidizer Valve on the GUI.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 65,
      role: "CS to PD",
      name: "/FlightComputer/launch",
      comment:
        "Press the \"Launch\" button on the control box after countdown from 3 over radio: Confirm that the Main Oxidizer Valve is energized by hearing a 'click' sound from its pilot and receiving an acknowledgment.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 66,
      role: "CS",
      name: "/FlightComputer/reset_prop_boards_valve_state",
      comment:
        'Press the "Reset Prop" button on the GUI: confirm that Main Oxidizer Valve is disarmed and de-energized. Note: this command might take a few seconds to be executed due to the FCs being in launch mode.',
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 67,
      role: "CS",
      name: "/FlightComputer/reset_av",
      comment:
        'Press the "Reset FC" button on the GUI: confirm that the ACK for the reset command is received.',
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 68,
      role: "CS",
      name: "/FlightComputer/propulsion_on",
      comment: 'Energize the propulsion controllers by pressing the "Prop On" button on the GUI.',
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 69,
      role: "CS",
      name: "/FlightComputer/emergency_stop",
      comment:
        'Release the "Launch" button on the control box and disarm the control box with the key.',
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 70,
      role: "CS to PD",
      commands: [
        {
          name: "/FlightComputer/vent_valve_energize",
        },
        {
          name: "/FlightComputer/vent_valve_de-energize",
        },
      ],
      comment: "Energize and de-energize the vent valve [V-12] after countdown from 3 over radio.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 71,
      role: "PD",
      text: "Give the arming key to OP1, who arms the pad box after a countdown from 3 over radio.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 72,
      role: "LD",
      text: "Give the testing arming key to CS",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 73,
      role: "CS",
      name: "/FlightComputer/mov_arming",
      comment: "Arm the propulsion system using the testing arming key.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 74,
      role: "OP3",
      text: "Probe the WAGO connectors connected to the igniter leads with a multimeter set to measure voltage.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 75,
      role: "CS",
      name: "",
      comment: "Send a signal for IGN- after a countdown from 3 over radio.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 76,
      role: "OP3",
      text: "Confirm to PD that voltmeter is reading 0V",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 77,
      role: "CS",
      name: "/LabJackT7/write_digital_pin",
      arguments: [
        { name: "pin_number", value: 20 },
        { name: "pin_state", value: "HIGH" },
      ],
      comment: "Send a signal for IGN+ after a countdown from 3 over radio.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 78,
      role: "OP3",
      text: "Confirm to PD that the multimeter is reading 24V.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 79,
      role: "CS",
      name: "",
      comment: "Set both IGN- and IGN+ to low",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 80,
      role: "OP3",
      text: "Confirm to PD that the multimeter is reading 0V.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 81,
      role: "CS",
      name: "/FlightComputer/mov_disarming",
      comment:
        "Disarm the propulsion system by removing the testing arming key. Give the arming key back to LD",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 82,
      role: "OP4",
      text: "Disarm the pad box using the arming key then give the key back to PD.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 83,
      role: "LD",
      text: "Announce Go/No-Go for propulsion system purge: _____",
    }),
    ProcedureStep.make({
      type: "note",
      text: "LAUNCH DIRECTOR: if propulsion purge test is being skipped, proceed to step 137",
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 84,
      role: "OP1",
      text: "Complete the flexible hose connection between the fill panel and the nitrogen mother tank. Do not forget the pressure regulator. UNPLUG THE ENDS OF THE FLEXIBLE HOSE.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 85,
      role: "OP1 & PD",
      text: "Verify that the nitrogen CGA fitting is correctly installed.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 86,
      role: "OP3 & OP4",
      text: "Stand next to manual dump lines.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 87,
      role: "OP1",
      text: "Confirm that the connection between the nitrogen mother tank and the flexible hose is properly tightened.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 88,
      role: "LD & PD",
      text: "Confirm again that the ground station and launch pad generators are full of gas. Fill them if necessary.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 89,
      role: "PD to LD",
      text: "Confirm readiness to begin propulsion system purge procedures.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 90,
      role: "CS",
      name: "",
      comment:
        "Confirm that the FDOV is de-energized and open, and continuity is true (dot for FDOV is green).",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 91,
      role: "CS",
      name: "",
      comment:
        "Confirm that the vent valve [V-12] is de-energized and open, and that continuity is true (dot for the vent valve is green).",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 92,
      role: "CS",
      name: "",
      comment:
        "Confirm that the MOV is de-energized and closed, and that continuity is true (dot for main oxidizer valve is green).",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 93,
      role: "CS",
      name: "",
      comment: "Confirm the panel fill valve [V-22] is de-energized and closed.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 94,
      role: "LD & CS",
      text: "From now on until the system is safed, monitor the pad pressure and tank pressure to ensure they don't exceed 150 psi.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 95,
      role: "LD",
      text: "Confirm that the panel pressure and temperature sensors are reading ambient values.\n\nPre-fill Pressure: _____ psi\nPost-fill Pressure: _____ psi\nPre-fill Temperature: _____ °C",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 96,
      role: "OP1",
      text: "Confirm nitrogen pressure regulator [R51] is fully backed off.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 97,
      role: "LD to PD",
      text: "Grant permission to open the nitrogen mother tank needle valve [V-50].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 98,
      role: "OP1",
      text: "Slowly open the mother tank needle valve [V-50] fully and then back a quarter turn.",
    }),
    ProcedureStep.make({
      type: "note",
      text: "Warning: Launch Pad personnel are now in a hazardous environment (nitrogen gas).",
      color: "#FEBFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 99,
      role: "PD to LD",
      text: "Confirm that nitrogen mother tank needle valve [V-50] is open",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 100,
      role: "LD",
      text: "Confirm that the panel pressure and temperature sensors are still reading ambient values. Pressure: _____ psi Temperature: _____ °C",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 101,
      role: "LD to PD",
      text: "Grant permission to open the nitrogen pressure regulator [R-11] to a pressure of 150 psi.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 102,
      role: "OP1",
      text: "Slowly open the pressure regulator [R-11] until a pressure of 150 psi is read on the outlet gauge, reading off every 50 psi.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 103,
      role: "LD",
      text: "Confirm that the panel pressure and temperature sensors are reading values in the expected range (prefill 150 psi, postfill 14.7 psi)\n\nPre-fill Pressure: _____ psi\nPost-fill Pressure: _____ psi\nPre-fill Temperature: _____ °C",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 104,
      role: "PD",
      text: "Direct all operators to leave the tower raising safety radius.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 105,
      role: "PD to LD",
      text: "Confirm the tower raising safety radius is clear of pad operators.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 106,
      role: "CS",
      name: "/LabJackT7/write_digital_pin",
      arguments: [
        { name: "pin_number", value: 1 },
        { name: "pin_state", value: "HIGH" },
      ],
      comment: "Energize the panel dump valve [V-23] to close.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 107,
      role: "CS & PD",
      name: "",
      comment: "Confirm that the panel dump valve [V-23] is closed.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 108,
      role: "CS",
      name: "/FlightComputer/vent_valve_energize",
      comment: "Energize the vent valve [V-12] to close.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 109,
      role: "CS & PD",
      name: "",
      comment: "Confirm that the vent valve [V-12] is closed.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 110,
      role: "CS",
      name: "/LabJackT7/write_digital_pin",
      arguments: [
        { name: "pin_number", value: 0 },
        { name: "pin_state", value: "HIGH" },
      ],
      comment: "Energize the panel fill valve [V-22] to open.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 111,
      role: "LD",
      text: "Confirm that the panel and tank pressure and temperature sensors are reading values in the expected range (prefill, postfill and tank 150 psi).\n\nPre-fill Pressure: _____ psi\nPost-fill Pressure: _____ psi\nPre-fill Temperature: _____ °C\nTank Pressure: _____ psi\nTank Temperature: _____ °C",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 112,
      role: "LD",
      text: "Confirm that the pressure in the tank has stabilized.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 113,
      role: "CS",
      name: "/LabJackT7/write_digital_pin",
      arguments: [
        { name: "pin_number", value: 0 },
        { name: "pin_state", value: "LOW" },
      ],
      comment: "De-energize the panel fill valve [V-22] to close.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 114,
      role: "LS & PD",
      text: "Confirm the panel fill valve [V-22] is closed.",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 115,
      role: "CS",
      name: "",
      comment: "Energize the panel dump valve [V-23] to open.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 116,
      role: "LD",
      text: "Wait 5 seconds for purge to complete.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 117,
      role: "LD",
      text: "Confirm that the panel and tank pressure and temperature sensors are reading values in the expected range (prefill 150 psi, postfill and tank 14.7 psi).\n\nPre-fill Pressure: _____ psi\nPost-fill Pressure: _____ psi\nPre-fill Temperature: _____ °C\nTank Pressure: _____ psi\nTank Temperature: _____ °C",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 118,
      role: "CS",
      name: "",
      comment: "De-energize the panel dump valve [V-23] to close.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 119,
      role: "LD",
      text: "Grant permission for operators to enter the tower raise safety radius.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 120,
      role: "PD",
      text: "Instruct operators to return to the pad.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 121,
      role: "OP1",
      text: "Close nitrogen mother tank needle valve [V-50].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 122,
      role: "PD to LD",
      text: "Confirm nitrogen mother tank needle valve [V-50] is fully closed.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 123,
      role: "LD to PD",
      text: "Grant permission to vent the prefill section through manual dump valve [V-21].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 124,
      role: "PD",
      text: "Stabilize the fill panel to prevent it from wobbling during venting",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 125,
      role: "OP5",
      text: "Slowly open manual dump valve [V-21].Wait 5 seconds.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 126,
      role: "LD",
      text: "Confirm that the panel pre-fill pressure has dropped to ambient values. Pre-fill Pressure: _____ psi",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 127,
      role: "LD to PD",
      text: "Confirm venting is complete.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 128,
      role: "OP1",
      text: "Fully back off nitrogen pressure regulator [R11].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 129,
      role: "OP2",
      text: "Close manual dump valve [V-21].",
    }),
    ProcedureStep.make({
      type: "command",
      stepNumber: 130,
      role: "CS",
      name: "/FlightComputer/vent_valve_de-energize",
      comment: "De-energize to open vent valve [V-12].",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 131,
      role: "PD to LD",
      text: "Confirm the end of purge procedures.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 132,
      role: "OP1",
      text: "Disconnect the flexible hose connection between the fill panel and the nitrogen mother tank. BE SURE TO PLUG THE ENDS OF THE FLEXIBLE HOSE.",
    }),
    ProcedureStep.make({
      type: "note",
      text: 'If waiting for a salvo, to conserve battery life, turn off the propulsion controllers on the GUI with the "Prop Off" button. Turn off the flight computers by inserting the respective pull pins into Arming Board A. Undo these steps before proceeding.',
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 133,
      role: "PD",
      text: "Confirm Go/No-Go to Filling and Arming for Launch Procedures [TW3] on the launch pad side: _____",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 134,
      role: "LD",
      text: "Confirm Go/No-Go to Filling and Arming for Launch Procedures [TW3] on the ground station side: _____",
    }),
    ProcedureStep.make({
      type: "note",
      text: "If state is No-Go, move to the appropriate procedures to resolve the problem.",
      color: "#FFDFBF",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 135,
      role: "PD",
      text: "If state is Go For Launch, direct all non-essential personnel to leave the launch pad.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 136,
      role: "OP1 & OP5",
      text: "Remove any foreign objects, and use a rake to remove any dried/flammable brush and foliage.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 137,
      role: "OP2 & OP4",
      text: "Use filled water canister to wet the ground under the rocket especially under the deflector plate and where the igniter leads will land.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 138,
      role: "OP3",
      text: "Check that all connections coming out of the padbox to the launch pad components are continuous.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 139,
      role: "PD",
      text: "Perform an operator headcount. Number of people at the launch pad: _____ Expected: 6.",
    }),
    ProcedureStep.make({
      type: "text",
      stepNumber: 140,
      role: "LD",
      text: "Perform a headcount of everyone at the ground station. Call for personnel to no longer move between competition locations. Number of people at the ground station: _____",
    }),
  ],
});
