import { ProcedureStep } from "@mrt/yamcs-effect";

export const finalSimultaneousChecksSteps = [
  ProcedureStep.make({
    type: "note",
    text: "The following steps can be done simultaneously and are organized by LD/PD.",
    color: "#FFDFBF",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 56,
    role: "OP1 & OP5",
    text: [
      "1. Remove foreign objects and flammables from launch pad, including tower supports",
      "2. Secure rail stop",
      "3. Stand by for igniter placement",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 57,
    role: "OP3",
    text: "Confirm there are no wires going above the retraction arm and close to the tower that could get caught on the fins.",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 58,
    role: "OP2 & OP4",
    text: [
      "1. Wet ground in front of deflector plate",
      "2. Reinstall ignitor shield",
      "3. Return to safety radius and stand at manual dump lines",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 59,
    role: "OP3",
    text: [
      "1. Adjust deflector plate camera",
      "2. Broadcast to PD and LD that SRAD system is about to be turned on",
      "3. Turn on the SRAD system with the SRAD electromagnet by flipping the SRAD switch to the on/off position on the Pad Box.",
      "4. Broadcast to PD and LD that COTS system is about to be turned on",
      "5. Turn on COTS system while broadcasting to LD and PD that it is being done. OP3 should confirm that the COTS system is powered on using the Blue Raven app.",
      "6. Do a final continuity check",
      "7. Return to safety radius",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "note",
    text: "Warning: The ejection system is now ON",
    color: "#FEBFBF",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 60,
    role: "PD to LD",
    text: "Relay successful COTS & Pyro activation.",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 61,
    role: "AV to PD",
    text: "Confirm reception of telemetry and payload data from the AV bay over radio.",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 62,
    role: "AV",
    name: "/FlightComputer/propulsion_on",
    comment: 'Energize the propulsion controllers by pressing the "Prop On" button on the GUI.',
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 63,
    role: "LD to PD",
    text: "Announce the start of rocket valve actuation tests",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 64,
    role: "CS",
    commands: [
      { name: "/FlightComputer/fdov_energize" },
      { name: "/FlightComputer/fdov_de-energize" },
      { name: "/FlightComputer/vent_valve_energize" },
      { name: "/FlightComputer/vent_valve_de-energize" },
    ],
    comment:
      "Energize and De-Energize the following valves, confirming actuation using Cameras and the GUI.\nFDOV Valve V-11 NO:\nVent Valve V-12 NO:",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 65,
    role: "AV",
    name: "/FlightComputer/arm_recovery",
    comment: "Press the command stack button to set Recovery Arm.",
  }),
  ProcedureStep.make({
    type: "verify",
    stepNumber: 66,
    role: "AV",
    presentation: {
      type: "truthTable",
      columns: [
        { id: "logicalArm", label: "Logical Arm" },
        { id: "electricalArm", label: "Electrical Arm" },
        { id: "continuity", label: "Electrical Continuity" },
      ],
    },
    condition: [
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_SW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "logicalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_HW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "electricalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_continuity_HW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "continuity" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_armed_SW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "logicalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_armed_HW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "electricalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_continuity_HW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "continuity" },
      },
    ],
    delay: 0,
    comment:
      "Confirm that the completion ACK is received.\nConfirm the ejection channel states are as follows:",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 67,
    role: "AV",
    name: "/FlightComputer/umbilical_to_battery",
    comment: "Press the command stack button to set Umbilical Low.",
  }),
  ProcedureStep.make({
    type: "verify",
    stepNumber: 67,
    role: "AV",
    condition: [
      {
        parameter: "/SystemA/Rocket/FlightComputer/external_power_hw",
        operator: "eq",
        value: false,
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/external_power_sw",
        operator: "eq",
        value: false,
      },
    ],
    delay: 0,
    comment: "Confirm that External Power HW and External Power SW are both FALSE.",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 68,
    role: "CS",
    text: "Arm the control box with the testing arming key.",
  }),
  ProcedureStep.make({
    type: "verify",
    stepNumber: 69,
    role: "AV",
    condition: [
      {
        parameter: "/SystemA/Rocket/FlightComputer/mov_continuity_HW",
        operator: "eq",
        value: true,
      },
    ],
    delay: 0,
    comment: "Confirm that there is continuity of the Main Oxidizer Valve MOV [V-13] on the GUI.",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 70,
    role: "CS to PD",
    name: "/FlightComputer/launch",
    comment:
      'Press the "Launch" button on the control box after countdown from 3 over radio: Confirm that the Main Oxidizer Valve MOV is energized by receiving an acknowledgment.',
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 71,
    role: "AV",
    name: "/FlightComputer/reset_av",
    comment:
      'Press the "Reset FC" button on the GUI: confirm that the ACK for the reset command is received.',
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 72,
    role: "AV",
    name: "/FlightComputer/gps_debug_on",
    comment: "Press the command stack button to Enable GPS Debug.",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 73,
    role: "AV",
    name: "/FlightComputer/propulsion_on",
    comment: 'Energize the propulsion controllers by pressing the "Prop On" button on the GUI.',
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 74,
    role: "CS",
    text: 'Release the "Launch" button on the control box and disarm the control box with the key.',
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 75,
    role: "LD",
    text: [
      "Confirm that the following sensors are reading ambient values.",
      "",
      "Pre-fill Pressure: _____ psi",
      "Post-fill Pressure: _____ psi",
      "Tank Pressure: _____ psi",
      "Combustion Chamber Pressure: _____ psi",
      "Pre-fill Temperature: _____ °C",
      "Tank Temperature: _____ °C",
      "Vent Temperature: _____ °C",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 76,
    role: "LD",
    text: [
      "Confirm that the GPS data is credible (should indicate a position near LC vertical launch area, 47.98737, -81.84874.) and that the Altitude is giving credible data (approx at 400m)",
      "",
      "GPS values: ____________________",
      "Altitude values: _____ ft/m",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 77,
    role: "AV",
    name: "/FlightComputer/gps_debug_off",
    comment: "Press the command stack button to Disable GPS Debug.",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 78,
    role: "AV to LD",
    text: [
      "Confirm that the Featherweight GPS data is credible (should indicate a position near LC vertical launch area, 47.98737, -81.84874.) and that the Altitude is giving credible data (approx at 400m)",
      "",
      "GPS values: ____________________",
      "Altitude values: _____ ft/m",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 79,
    role: "PD to LD",
    text: "Confirm that all the rocket panels are on",
  }),
];
