import { ProcedureStep } from "@mrt/yamcs-effect";

export const recoverySubSystemCommandAndTelemetryVerificationSteps = [
  ProcedureStep.make({
    type: "note",
    text: "Recovery Sub-System Command and Telemetry Verification",
    color: "#FFBF80",
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 13,
    role: "CSH",
    name: "/FlightComputer/arm_recovery",
    comment: "Press the command stack button to set Recovery Arm.",
  }),
  ProcedureStep.make({
    type: "verify",
    stepNumber: 14,
    role: "CSC",
    presentation: {
      type: "truthTable",
      columns: [
        { id: "logicalArm", label: "Logical Arm" },
        { id: "electricalArm", label: "Electrical Arm" },
        { id: "continuity", label: "Electrical Continuity" },
      ],
    },
    condition: [
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_SW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "logicalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_HW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "electricalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_continuity_HW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "continuity" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_armed_SW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "logicalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_armed_HW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "electricalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_continuity_HW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "continuity" },
      },
    ],
    delay: 0,
    comment:
      "Confirm that the completion ACK is received.\nConfirm the ejection channel states are as follows:",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 15,
    role: "AVC",
    text: [
      "Confirm the LEDs on the FC-A Energize Daughter Board are as follows:",
      "  Channel  ARM  GATE  EN  CON",
      "  CH1      on   off   off on",
      "  Channel  CON  GATE  EN  ARM",
      "  CH2      on   off   off on",
      "Confirm the LEDs on the FC-B Energize Daughter Board are as follows:",
      "  Channel  ARM  GATE  EN  CON",
      "  CH1      on   off   off on",
      "  Channel  CON  GATE  EN  ARM",
      "  CH2      on   off   off on",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "command",
    stepNumber: 16,
    role: "CSH",
    name: "/FlightComputer/disarm_recovery",
    comment: "Press the command stack button to set Recovery Disarm.",
  }),
  ProcedureStep.make({
    type: "verify",
    stepNumber: 17,
    role: "CSC",
    presentation: {
      type: "truthTable",
      columns: [
        { id: "logicalArm", label: "Logical Arm" },
        { id: "electricalArm", label: "Electrical Arm" },
        { id: "continuity", label: "Electrical Continuity" },
      ],
    },
    condition: [
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_SW",
        operator: "eq",
        value: false,
        display: { row: "Drogue", column: "logicalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_armed_HW",
        operator: "eq",
        value: false,
        display: { row: "Drogue", column: "electricalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/drogue_continuity_HW",
        operator: "eq",
        value: true,
        display: { row: "Drogue", column: "continuity" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_armed_SW",
        operator: "eq",
        value: false,
        display: { row: "Main", column: "logicalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_armed_HW",
        operator: "eq",
        value: false,
        display: { row: "Main", column: "electricalArm" },
      },
      {
        parameter: "/SystemA/Rocket/FlightComputer/main_continuity_HW",
        operator: "eq",
        value: true,
        display: { row: "Main", column: "continuity" },
      },
    ],
    delay: 0,
    comment:
      "Confirm that the completion ACK is received.\nConfirm the ejection channel states are as follows:",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 18,
    role: "AVC",
    text: [
      "Confirm the LEDs on the FC-A Energize Daughter Board are as follows:",
      "  Channel  ARM  GATE  EN  CON",
      "  CH1      off  off   off on",
      "  Channel  CON  GATE  EN  ARM",
      "  CH2      on   off   off off",
      "Confirm the LEDs on the FC-B Energize Daughter Board are as follows:",
      "  Channel  ARM  GATE  EN  CON",
      "  CH1      off  off   off on",
      "  Channel  CON  GATE  EN  ARM",
      "  CH2      on   off   off off",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 19,
    role: "AVC",
    text: [
      "Confirm the LEDs on the IEPE PCB are as follows:",
      "  LED    State",
      "  VBAT   ON",
      "  5V0    ON",
      "  3V3    ON",
      "  LED_1  blinking at a rate of 1 Hz",
      "  LED_2  OFF",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 20,
    role: "CSC",
    text: [
      "Confirm telemetry link for the IEPE PCB is established by confirming that the payload states are as follows:",
      "  Variable             State",
      "  pa_ok                TRUE",
      "  pa_sampling_state    TRUE",
      "  pa_amplitude_x       stable",
      "  pa_amplitude_y       stable",
      "  pa_amplitude_z       stable",
      "  pa_frequency_x       stable",
      "  pa_frequency_y       stable",
      "  pa_frequency_z       stable",
    ].join("\n"),
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 21,
    role: "AVC",
    text: "Confirm that on the Adapter PCB, both the 3V3 and 5V LEDs are on.",
  }),
  ProcedureStep.make({
    type: "text",
    stepNumber: 22,
    role: "AVC",
    text: "Disarm SRAD avionics.",
  }),
];
